### PR TITLE
Merged Metadata component

### LINKED ISSUE #82: Merge metadata and property observer components
Since they are fairly simple and only used in this package, it would be best to simply extract the used functionality and deprecate the standalone packages.

### PR DESCRIPTION
**Pull request by szymach**
Resolves #82

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by chives** [comment]
we should remove `fsi/metadata` from `composer.json`

**Comment by szymach** [comment]
"We"

**Comment by szymach** [comment]
@fsi-open Scrutinizer is up to 7/10 now :)

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@JarekW @rn0

**Comment by szymach** [comment]
@rn0

**Pull request merged**
